// generate-wallets.mjs
// Generates two throwaway EVM keypairs for the demo:
//   1. AGENT wallet  - acts as the paying AI agent (the x402 client)
//   2. PUBLISHER wallet - receives the USDC payment (the x402 resource server's payTo address)
//
// Usage:
//   npm install viem
//   node generate-wallets.mjs
//
// This writes a .env file (git-ignored) with both keys/addresses.
// NEVER commit .env or reuse these keys for anything beyond Base Sepolia testnet.

import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import fs from "node:fs";

function makeWallet(label) {
  const privateKey = generatePrivateKey();
  const account = privateKeyToAccount(privateKey);
  console.log(`\n${label}`);
  console.log(`  address:     ${account.address}`);
  console.log(`  private key: ${privateKey}`);
  return { privateKey, address: account.address };
}

const agent = makeWallet("AGENT WALLET (the paying AI agent)");
const publisher = makeWallet("PUBLISHER WALLET (receives USDC payments)");

const envContents = `# Base Sepolia demo wallets - generated by generate-wallets.mjs
# DO NOT commit this file or reuse these keys outside of Base Sepolia testnet.

AGENT_PRIVATE_KEY=${agent.privateKey}
AGENT_ADDRESS=${agent.address}

PUBLISHER_PRIVATE_KEY=${publisher.privateKey}
PUBLISHER_ADDRESS=${publisher.address}

# Fill these in:
BASE_SEPOLIA_RPC_URL=https://sepolia.base.org
FACILITATOR_URL=https://x402.org/facilitator
RESOURCE_URL=https://<your-akamai-functions-app>.aka.fermyon.tech/
`;

fs.writeFileSync(new URL("../.env", import.meta.url), envContents);

console.log(`\nWrote .env with both wallets.`);
console.log(`\nNext steps:`);
console.log(`  1. Fund AGENT_ADDRESS with test USDC:  https://faucet.circle.com/  (select Base Sepolia)`);
console.log(`  2. (optional) Fund AGENT_ADDRESS with a little test ETH for gas: https://www.alchemy.com/faucets/base-sepolia`);
console.log(`  3. Run check-balances.mjs to confirm funds landed.`);
